Remove bitcore node dependency
HorizenLabs/sc_auditchain_explorer pull request #9
Opened 2021-12-29 16:53 UTC by otoumas

In this PR the needed changes to use the node package of bitcore-module-sidechain are done. The changes are:
- Dependency: npm package instead of git repository
- Changes in import to adjust to new package
- Changes in Dockerfile to adjust to new package

2021-12-29 17:25 UTC, cronicc requested changes

2021-12-29 17:25 UTC, cronicc commented on .gitignore
>  bitcore.config.json
Please commit package-lock.json

2021-12-29 17:25 UTC, cronicc commented on Dockerfile
>      && npm run compile
Unless our nodejs code can handle signals (SIGINT, SIGTERM) and reap zombie processes an init system should be used like https://github.com/krallin/tini.

See: https://developpaper.com/avoid-running-nodejs-as-pid-1-under-the-docker-image/

2021-12-29 17:25 UTC, cronicc commented on package.json
>    "license": "ISC",
```
  "engines": {
    "node": ">=16"
  },
```

2021-12-29 17:25 UTC, cronicc commented on tsconfig.json
> +    "target": "ES2019",
If node 16 is required, ES2021 could be used, see https://stackoverflow.com/questions/67371787/what-typescript-configuration-produces-output-closest-to-node-js-16-capabilities/67371788#67371788

2021-12-30 09:42 UTC, MarcoOl94 commented on README.md
>  - Check that you have permissions for these three repos: `bitcore-module-sidechain`, `sc-bitcore-node-zen`
I think sc-bitcore-node-zen was merged into bitcore-module-sidechain, if it's true remove it from the README please.

2021-12-30 10:47 UTC, paolocappelletti requested changes

2021-12-30 14:38 UTC, cronicc approved these changes

2021-12-30 14:47 UTC, cronicc commented on README.md
>  - `npm install`
```suggestion
- `npm ci`
```

2021-12-31 14:00 UTC, merged